### ISSUE TITLE
Reuse of lenses across projects

### ISSUE THREAD

**Issue by matanster** [salesforce/refocus-ldk#11]
More of a conceptual issue, but is the API accompanied by UI templates that can be picked from, or does each implementation team have to invent their own UI wheel?

The [blog announcement](https://medium.com/salesforce-open-source/take-a-moment-to-refocus-86b6546c90c) touts several intricate lenses, but I had not noticed any lead as to how to reproduce or leverage any of them. It even boasts that a database team managed to create one of the lenses, but your typical database team is not a front-end development team!

E.g. the blog says, quote
>  So we designed a flexible, hierarchical data model which could be adapted to just about any use case.

Will you be open sourcing this and similar lenses, sans any proprietary or specific service configuration code? 

It would be otherwise quite confounding how others can reap similar benefit without a team of UX and front-end people. If we have open-sourced templates, we can be much more agile about it and have more trust in the framework so as to leap into using it.

Differently put, it is great to have a neat and flexible architecture for service monitoring with visualization, but open-sourced templates speed up adoption and community support, as well as they importantly contribute the side benefit of providing more code examples than a documentation-set alone can offer.

**Comment by iamigo** [comment]
I agree whole-heartedly. We have open sourced two of our lenses:

- https://github.com/salesforce/refocus-lens-multitable
- https://git.soma.salesforce.com/igoldstein/refocus-lens-tree

We will continue to open source more lenses as we develop them. We have two more which we still haven't moved to public github, coming soon. My hope is that as other folks develop their own lenses, they will open source them, too!

I will add a wiki page to this repo where anyone can link to their own lens repo.

**Comment by matanster** [comment]
@iamigo this sounds terrific. thanks for posting here and a wiki page for lenses should likely promote adoption!
