### ISSUE TITLE
Broken url in example lens code

### ISSUE THREAD

**Issue by matanster** [salesforce/refocus-ldk#12]
we have one example at https://github.com/salesforce/refocus-ldk/blob/master/Lenses/Example/lens.json, without a live url demonstrating it, or the url is just broken.

**Comment by iamigo** [comment]
Oops--that "helpUrl" was linking to our old internal repo. I have updated the link, but it doesn't actually link to a live demo of the lens... we're still working on standing up a public Refocus instance with some sample data and examples of the different lenses :(

**Comment by matanster** [comment]
Good to know! do you have an announcements list or something, or do you
just use medium and social media for updates?

**Comment by iamigo** [comment]
We don't have an announcements list... you can "watch" the repo, although that may end up feeling a little spammy... let me check with my PM.
